nohup python runner.py --dataset_folder /home/VD/kaveri/sharedtask2021/data/ --dataset_name spa.rst.sctb --save_model_dir ./refined_runs --refinement True --cuda 2 > refined_runs/runtime_spa.rst.sctb.out 2> refined_runs/runtime_spa.rst.sctb.err &
# nohup python runner.py --dataset_folder /home/VD/kaveri/sharedtask2021/data/ --dataset_name spa.rst.rststb --save_model_dir ./refined_runs --refinement True --cuda 4 > refined_runs/runtime_spa.rst.rststb.out 2> refined_runs/runtime_spa.rst.rststb.err &
# nohup python runner.py --dataset_folder /home/VD/kaveri/sharedtask2021/data/ --dataset_name zho.rst.sctb --save_model_dir ./refined_runs --refinement True --cuda 5 > refined_runs/runtime_zho.rst.sctb.out 2> refined_runs/runtime_zho.rst.sctb.err &
# nohup python runner.py --dataset_folder /home/VD/kaveri/sharedtask2021/data/ --dataset_name deu.rst.pcc --save_model_dir ./refined_runs --refinement True --cuda 0 > refined_runs/runtime_deu.rst.pcc.out 2> refined_runs/runtime_deu.rst.pcc.err &
# nohup python runner.py --dataset_folder /home/VD/kaveri/sharedtask2021/data/ --dataset_name nld.rst.nldt --save_model_dir ./refined_runs --refinement True --cuda 0 > refined_runs/runtime_nld.rst.nldt.out 2> refined_runs/runtime_nld.rst.nldt.err &
# nohup python runner.py --dataset_folder /home/VD/kaveri/sharedtask2021/data/ --dataset_name por.rst.cstn --save_model_dir ./refined_runs --refinement True --cuda 5 > refined_runs/runtime_por.rst.cstn.out 2> refined_runs/runtime_por.rst.cstn.err &
# nohup python runner.py --dataset_folder /home/VD/kaveri/sharedtask2021/data/ --dataset_name fra.sdrt.annodis --save_model_dir ./refined_runs --refinement True --cuda 4 > refined_runs/runtime_fra.sdrt.annodis.out 2> refined_runs/runtime_fra.sdrt.annodis.err &
# nohup python runner.py --dataset_folder /home/VD/kaveri/sharedtask2021/data/ --dataset_name fas.rst.prstc --save_model_dir ./refined_runs --refinement True --cuda 1 > refined_runs/runtime_fas.rst.prstc.out 2> refined_runs/runtime_fas.rst.prstc.err &
# nohup python runner.py --dataset_folder /home/VD/kaveri/sharedtask2021/data/ --dataset_name eus.rst.ert --save_model_dir ./refined_runs --refinement True --cuda 0 > refined_runs/runtime_eus.rst.ert.out 2> refined_runs/runtime_eus.rst.ert.err &
# nohup python runner.py --dataset_folder /home/VD/kaveri/sharedtask2021/data/ --dataset_name eng.sdrt.stac --save_model_dir ./refined_runs --refinement True --cuda 0 > refined_runs/runtime_eng.sdrt.stac.out 2> refined_runs/runtime_eng.sdrt.stac.err &
#epochs = 10
# nohup python runner.py --dataset_folder /home/VD/kaveri/sharedtask2021/data/ --dataset_name tur.pdtb.tdb --save_model_dir ./refined_runs --refinement True --cuda 0 > refined_runs/runtime_tur.pdtb.tdb.out 2> refined_runs/runtime_tur.pdtb.tdb.err &
# nohup python runner.py --dataset_folder /home/VD/kaveri/sharedtask2021/data/ --dataset_name eng.rst.rstdt --save_model_dir ./refined_runs --refinement True --cuda 4 > refined_runs/runtime_eng.rst.rstdt.out 2> refined_runs/runtime_eng.rst.rstdt.err &
# nohup python runner.py --dataset_folder /home/VD/kaveri/sharedtask2021/data/ --dataset_name eng.rst.gum --save_model_dir ./refined_runs --refinement True --cuda 4 > refined_runs/runtime_eng.rst.gum.out 2> refined_runs/runtime_eng.rst.gum.err &
# nohup python runner.py --dataset_folder /home/VD/kaveri/sharedtask2021/data/ --dataset_name rus.rst.rrt --save_model_dir ./refined_runs --refinement True --cuda 2 > refined_runs/runtime_rus.rst.rrt.out 2> refined_runs/runtime_rus.rst.rrt.err &
# nohup python runner.py --dataset_folder /home/VD/kaveri/sharedtask2023/data/ --dataset_name eng.pdtb.pdtb --save_model_dir ./refined_runs --refinement True --cuda 2 > refined_runs/runtime_eng.pdtb.pdtb.out 2> refined_runs/runtime_eng.pdtb.pdtb.err &
# nohup python runner.py --dataset_folder /home/VD/kaveri/sharedtask2023/data/ --dataset_name zho.rst.gcdt --save_model_dir ./refined_runs --refinement True --cuda 0 > refined_runs/runtime_zho.rst.gcdt.out 2> refined_runs/runtime_zho.rst.gcdt.err &
# nohup python runner.py --dataset_folder /home/VD/kaveri/sharedtask2023/data/ --dataset_name tha.pdtb.tdtb --save_model_dir ./refined_runs --refinement True --cuda 6 > refined_runs/runtime_tha.pdtb.tdtb.out 2> refined_runs/runtime_tha.pdtb.tdtb.err &
# nohup python runner.py --dataset_folder /home/VD/kaveri/sharedtask2023/data/ --dataset_name ita.pdtb.luna --save_model_dir ./refined_runs --refinement True --cuda 0 > refined_runs/runtime_ita.pdtb.luna.out 2> refined_runs/runtime_ita.pdtb.luna.err &
# nohup python runner.py --dataset_folder /home/VD/kaveri/sharedtask2023/data/ --dataset_name por.pdtb.crpc --save_model_dir ./refined_runs --refinement True --cuda 0 > refined_runs/runtime_por.pdtb.crpc.out 2> refined_runs/runtime_por.pdtb.crpc.err &
# nohup python runner.py --dataset_folder /home/VD/kaveri/sharedtask2023/data/ --dataset_name zho.dep.scidtb --save_model_dir ./refined_runs --refinement True --cuda 0 > refined_runs/runtime_zho.dep.scidtb.out 2> refined_runs/runtime_zho.dep.scidtb.err &





# nohup python runner.py --dataset_folder /home/VD/kaveri/sharedtask2021/data/ --dataset_name spa.rst.sctb --save_model_dir ./runs --refinement True --cuda 2 > runs/runtime_spa.rst.sctb.out 2> runs/runtime_spa.rst.sctb.err &
# nohup python runner.py --dataset_folder /home/VD/kaveri/sharedtask2021/data/ --dataset_name spa.rst.rststb --save_model_dir ./runs --refinement True --cuda 3 > runs/runtime_spa.rst.rststb.out 2> runs/runtime_spa.rst.rststb.err &
# nohup python runner.py --dataset_folder /home/VD/kaveri/sharedtask2021/data/ --dataset_name zho.rst.sctb --save_model_dir ./runs --refinement True --cuda 4 > runs/runtime_zho.rst.sctb.out 2> runs/runtime_zho.rst.sctb.err &
# nohup python runner.py --dataset_folder /home/VD/kaveri/sharedtask2021/data/ --dataset_name deu.rst.pcc --save_model_dir ./runs --refinement True --cuda 5 > runs/runtime_deu.rst.pcc.out 2> runs/runtime_deu.rst.pcc.err &
# nohup python runner.py --dataset_folder /home/VD/kaveri/sharedtask2021/data/ --dataset_name nld.rst.nldt --save_model_dir ./runs --refinement True --cuda 6 > runs/runtime_nld.rst.nldt.out 2> runs/runtime_nld.rst.nldt.err &
# nohup python runner.py --dataset_folder /home/VD/kaveri/sharedtask2021/data/ --dataset_name por.rst.cstn --save_model_dir ./runs --refinement True --cuda 7 > runs/runtime_por.rst.cstn.out 2> runs/runtime_por.rst.cstn.err &
# nohup python runner.py --dataset_folder /home/VD/kaveri/sharedtask2021/data/ --dataset_name fra.sdrt.annodis --save_model_dir ./runs --refinement True --cuda 4 > runs/runtime_fra.sdrt.annodis.out 2> runs/runtime_fra.sdrt.annodis.err &
# nohup python runner.py --dataset_folder /home/VD/kaveri/sharedtask2021/data/ --dataset_name fas.rst.prstc --save_model_dir ./runs --refinement True --cuda 4 > runs/runtime_fas.rst.prstc.out 2> runs/runtime_fas.rst.prstc.err &
# nohup python runner.py --dataset_folder /home/VD/kaveri/sharedtask2021/data/ --dataset_name eus.rst.ert --save_model_dir ./runs --refinement True --cuda 4 > runs/runtime_eus.rst.ert.out 2> runs/runtime_eus.rst.ert.err &
# nohup python runner.py --dataset_folder /home/VD/kaveri/sharedtask2021/data/ --dataset_name eng.sdrt.stac --save_model_dir ./runs --refinement True --cuda 4 > runs/runtime_eng.sdrt.stac.out 2> runs/runtime_eng.sdrt.stac.err &
# nohup python runner.py --dataset_folder /home/VD/kaveri/sharedtask2021/data/ --dataset_name tur.pdtb.tdb --save_model_dir ./runs --refinement True --cuda 0 > runs/runtime_tur.pdtb.tdb.out 2> runs/runtime_tur.pdtb.tdb.err &
# nohup python runner.py --dataset_folder /home/VD/kaveri/sharedtask2021/data/ --dataset_name eng.rst.rstdt --save_model_dir ./runs --refinement True --cuda 2 > runs/runtime_eng.rst.rstdt.out 2> runs/runtime_eng.rst.rstdt.err &
# nohup python runner.py --dataset_folder /home/VD/kaveri/sharedtask2021/data/ --dataset_name eng.rst.gum --save_model_dir ./runs --refinement True --cuda 4 > runs/runtime_eng.rst.gum.out 2> runs/runtime_eng.rst.gum.err &
# nohup python runner.py --dataset_folder /home/VD/kaveri/sharedtask2021/data/ --dataset_name rus.rst.rrt --save_model_dir ./runs --refinement True --cuda 5 > runs/runtime_rus.rst.rrt.out 2> runs/runtime_rus.rst.rrt.err &
# nohup python runner.py --dataset_folder /home/VD/kaveri/sharedtask2023/data/ --dataset_name eng.pdtb.pdtb --save_model_dir ./runs --refinement True --cuda 5 > runs/runtime_eng.pdtb.pdtb.out 2> runs/runtime_eng.pdtb.pdtb.err &
# nohup python runner.py --dataset_folder /home/VD/kaveri/sharedtask2023/data/ --dataset_name zho.rst.gcdt --save_model_dir ./runs --refinement True --cuda 0 > runs/runtime_zho.rst.gcdt.out 2> runs/runtime_zho.rst.gcdt.err &
# nohup python runner.py --dataset_folder /home/VD/kaveri/sharedtask2023/data/ --dataset_name tur.pdtb.tedm --save_model_dir ./runs --refinement True --cuda 5 > runs/runtime_tur.pdtb.tedm.out 2> runs/runtime_tur.pdtb.tedm.err &
# nohup python runner.py --dataset_folder /home/VD/kaveri/sharedtask2023/data/ --dataset_name tha.pdtb.tdtb --save_model_dir ./runs --refinement True --cuda 5 > runs/runtime_tha.pdtb.tdtb.out 2> runs/runtime_tha.pdtb.tdtb.err &
# nohup python runner.py --dataset_folder /home/VD/kaveri/sharedtask2023/data/ --dataset_name ita.pdtb.luna --save_model_dir ./runs --refinement True --cuda 0 > runs/runtime_ita.pdtb.luna.out 2> runs/runtime_ita.pdtb.luna.err &
# nohup python runner.py --dataset_folder /home/VD/kaveri/sharedtask2023/data/ --dataset_name zho.dep.scidtb --save_model_dir ./runs --refinement True --cuda 1 > runs/runtime_zho.dep.scidtb.out 2> runs/runtime_zho.dep.scidtb.err &
# nohup python runner.py --dataset_folder /home/VD/kaveri/sharedtask2023/data/ --dataset_name por.pdtb.crpc --save_model_dir ./runs --refinement True --cuda 5 > runs/runtime_por.pdtb.crpc.out 2> runs/runtime_por.pdtb.crpc.err &
